Github Actions: ensure generated files are up-to-date

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,14 +1,14 @@
 name: Code testing
 on:
-  pull_request:
+  pull_request_target:
     types:
       - opened
       - reopened
       - synchronize
 
 jobs:
-  laboratory-operator:
-    name: Laboratory Operator
+  operators:
+    name: Operators
     runs-on: ubuntu-latest
 
     steps:
@@ -29,11 +29,73 @@ jobs:
           curl -L -O "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_linux_${arch}.tar.gz"
           tar -zxvf kubebuilder_${version}_linux_${arch}.tar.gz
           mv kubebuilder_${version}_linux_${arch} kubebuilder && sudo mv kubebuilder /usr/local/
-  
+
       - name: Perform the tests
         working-directory: operators/
         run: |
           make test
+
+
+  operators-generated:
+    name: Operators (Generated manifests)
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          persist-credentials: false
+
+      - name: Setup Go
+        uses: actions/setup-go@v1
+        with:
+          go-version: 1.15
+
+      - name: Run the automatic generation
+        working-directory: operators/
+        run: |
+          make generate
+          make manifests
+
+      - name: Gather the differences
+        id: git-diff
+        run: |
+          output=$(git diff | head -n 100)
+          exit_code=$([ "${output}" ] && echo 1 || echo 0)
+
+          # Required to correctly manage multi-line outputs
+          output="${output//'%'/'%25'}"
+          output="${output//$'\n'/'%0A'}"
+          output="${output//$'\r'/'%0D'}"
+
+          echo "::set-output name=diff::${output}"
+
+          # Trigger a failure in case the diff is not empty
+          exit ${exit_code}
+
+      - name: Issue a comment in case the diff is not empty
+        uses: peter-evans/create-or-update-comment@v1
+        with:
+          token: ${{ secrets.CI_TOKEN }}
+          issue-number: ${{ github.event.pull_request.number }}
+          body: |
+            The generated files in the `operators/` folder appear to be out-of-date.
+
+            Please, ensure you are using the correct version of `controller-gen` and re-run:
+            ```
+            make generate
+            make manifests
+            ```
+
+            <details>
+              <summary>Here it is an excerpt of the diff:</summary>
+
+              ```diff
+              ${{ steps.git-diff.outputs.diff }}
+              ```
+            </details>
+          reactions: confused
+        if: failure()
 
 
   kubernetes-manifests:
